# Generated by Django 3.2.1 on 2021-05-05 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210505_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='registerd_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
