# Generated by Django 3.2.1 on 2021-05-05 20:59

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_registerd_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='registerd_users',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
