# Generated by Django 3.2.1 on 2021-05-05 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_alter_courses_registerd_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='registerd_users',
        ),
        migrations.AddField(
            model_name='courses',
            name='registerd_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
