# Generated by Django 3.2.4 on 2021-06-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courses_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
