# Generated by Django 3.2.4 on 2021-06-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210511_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Student', 'Student')], default='Student', max_length=255, null=True),
        ),
    ]
